services:
  transactionaloutboxmasstransit:
    image: transactionaloutboxmasstransit
    build:
      context: .
      dockerfile: TransactionalOutbox/TransactionalOutboxMassTransit/Dockerfile
    ports:
      - 8080:8888
    environment:
      - ASPNETCORE_HTTP_PORTS=8888
    depends_on:
      - postgresql
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
  
  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432

  masstransit_simple_publishermasstransitsimplepublisher:
    image: masstransit_simple_publishermasstransitsimplepublisher
    build:
      context: .
      dockerfile: Example MassTransit Pub Sub/MassTransit Simple Publisher/Dockerfile
    ports:
      - 8081:8889
    environment:
      - ASPNETCORE_HTTP_PORTS=8889

  masstransit_simple_consumer:
    image: masstransit_simple_consumer
    build:
      context: .
      dockerfile: Example MassTransit Pub Sub/MassTransit Simple Consumer/Dockerfile
    ports:
      - 8082:8890
    environment:
      - ASPNETCORE_HTTP_PORTS=8890

  masstransit_webapi_consumermasstransitwebapiconsumer:
    image: masstransit_webapi_consumermasstransitwebapiconsumer
    build:
      context: .
      dockerfile: Example MassTransit Pub Sub/MassTransit WebApi Consumer/Dockerfile
    ports:
      - 8083:8890
    environment:
      - ASPNETCORE_HTTP_PORTS=8890